version: '3.8'  # Specify the docker-compose version

services:
  auth:
    build:
      context: .
      dockerfile: ./Host/Auth/Dockerfile
    container_name: auth_container  # Build the image from the current directory (context)
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
      - "8081:8081"  # Map container port 8081 to host port 8081
      - "8082:8082"
    # depends_on:  # This service depends on no other services
    networks:
      - app-network

  hub:
    build:
      context: .
      dockerfile: ./Host/Hub/Dockerfile
    container_name: hub_container  # Build the image from the current directory (context)
    ports:
      - "7080:7080"  # Map container port 7080 to host port 7080
      - "7081:7081"  # Map container port 7081 to host port 7081
      - "7082:7082"
    # depends_on:  # This service depends on no other services
    networks:
      - app-network

  till:
    build:   # Build the image from the current directory (context)
      context: .
      dockerfile: ./Host/Till/Dockerfile
    container_name: till_container  # Build the image from the current directory (context)
    ports:
      - "6080:6080"  # Map container port 6080 to host port 6080 (different port than hub)
      - "6081:6081"  # Map container port 6081 to host port 6081
      - "6082:6082"
    # depends_on:  # This service depends on no other services
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_env03
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    extra_hosts:
      - "localhost: 10.10.2.82"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_env03
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTSIDE://10.10.2.82:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "localhost: 10.10.2.82"
    networks:
      - app-network

  kafkaUI:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_UI03
    ports:
      - 5080:5082
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    extra_hosts:
      - "localhost: 10.10.2.82"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "4080:4082"  # Expose Redis on the default port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
