version: '3.8'

services:

  authdb:
    image: postgres:16.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: AuthDB
    ports:
      - "5436:5432"
    volumes:
      - auth_local_shared_db:/var/lib/postgresql/data
    networks:
      - app-network

  hubdb:
    image: postgres:16.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: HubDB
    ports:
      - "5435:5432"
    volumes:
      - hub_local_shared_db:/var/lib/postgresql/data
    networks:
      - app-network

  storedb:
    image: postgres:16.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: storeDB
    ports:
      - "5437:5432"
    volumes:
      - store_local_shared_db:/var/lib/postgresql/data
    networks:
      - app-network

  store:
    image: storespecificimage # Use image from Docker Hub
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6080:6080"
      - "6081:6081"
      - "6082:6082"
    depends_on:  
      - storedb
    environment:
      - DB_HOST=storedb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=storeDB
    networks:
      - app-network

  hub:
    image: hubspecificimage  # Use image from Docker Hub
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
    depends_on:  
      - hubdb
      - redis
    environment:
      - DB_HOST=hubdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Pos!23
      - DB_NAME=HubDB
    networks:
      - app-network

  auth:
    image: authspecificimage  # Use image from Docker Hub
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "7080:7080"
      - "7081:7081"
      - "7082:7082"
    depends_on:  
      - authdb
    environment:
      - DB_HOST=authdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Pos!23
      - DB_NAME=AuthDB
    networks:
      - app-network

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  auth_local_shared_db:
  hub_local_shared_db:
  store_local_shared_db:

networks:
  app-network:
    driver: overlay
