version: '3.8'  # Specify the docker-compose version

services:

  authdb:
    image: postgres:latest
    container_name: authdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: AuthDB
    ports:
      - "0.0.0.0:5436:5432"
    volumes:
      - ./auth_local_shared_db:/var/lib/postgresql/data


  hubdb:
    image: postgres:latest
    container_name: hubdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: HubDB
    ports:
      - "0.0.0.0:5435:5432"
    volumes:
      - ./hub_local_shared_db:/var/lib/postgresql/data

  
  storedb:
    image: postgres:latest
    container_name: storedb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pos!23
      POSTGRES_DB: storeDB
    ports:
      - "0.0.0.0:5437:5432"
    volumes:
      - ./store_local_shared_db:/var/lib/postgresql/data


  store:
    build:   # Build the image from the current directory (context)
      context: .
      dockerfile: ./Host/Till/Dockerfile
    container_name: store_container 
    ports:
      - "0.0.0.0:6080:6080" 
      - "0.0.0.0:6081:6081"  
      - "0.0.0.0:6082:6082"
    depends_on:  
      - storedb
    environment:
      - DB_HOST=storedb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=storeDB


  hub:
    build:   # Build the image from the current directory (context)
      context: .
      dockerfile: ./Host/Hub/Dockerfile
    container_name: hub_container 
    ports:
      - "0.0.0.0:9080:9080" 
      - "0.0.0.0:9081:9081"  
      - "0.0.0.0:9082:9082"
    depends_on:  
      - hubdb
      - redis
    environment:
      - DB_HOST=hubdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Pos!23
      - DB_NAME=HubDB

 

  auth:
    build:   # Build the image from the current directory (context)
      context: .
      dockerfile: ./Host/Auth/Dockerfile
    container_name: auth_container 
    ports:
      - "0.0.0.0:7080:7080" 
      - "0.0.0.0:7081:7081"  
      - "0.0.0.0:7082:7082"
    depends_on:  
      - authdb
    environment:
      - DB_HOST=Authdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Pos!23
      - DB_NAME=AuthDB


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis on the default port

volumes:
  auth_local_shared_db:
    driver:
      local
  hub_local_shared_db:
    driver:
      local
  store_local_shared_db:
    driver:
      local
  






