// <auto-generated />
using System;
using DA.AppDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DM.DomainModels.Actions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("DM.DomainModels.Credential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Credential");

                    b.HasData(
                        new
                        {
                            Id = "10bcc73c-e40a-4852-a81d-c18d654e8806",
                            CreatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            IsActive = true,
                            IsArchived = false,
                            PasswordHash = "dTO+G05LJ3jW+Qkha4FYtQM5AG7hxPDM8/c6YJKYST4=",
                            PasswordSalt = "xZh0JAO/h8gD2dyrFOFiIw==",
                            UpdatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            UserId = "72990663-2edc-4c10-b331-cd1c65e477e0"
                        });
                });

            modelBuilder.Entity("DM.DomainModels.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SendToUserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetNamespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("DM.DomainModels.NotificationSeen", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("OnClickDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("NotificationSeen");
                });

            modelBuilder.Entity("DM.DomainModels.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("RevokeAble")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefereshToken");

                    b.HasData(
                        new
                        {
                            Id = "f3df99c7-07fb-4b7f-89e5-89d86b84bd41",
                            CreatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            ExpireyDate = new DateTime(2024, 10, 29, 9, 27, 20, 303, DateTimeKind.Utc).AddTicks(6553),
                            IsActive = true,
                            IsArchived = false,
                            RevokeAble = true,
                            Token = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            UserId = "72990663-2edc-4c10-b331-cd1c65e477e0"
                        });
                });

            modelBuilder.Entity("DM.DomainModels.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "78f4b56a-3fa3-4067-b641-7adb0a7a2ca7",
                            CreatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            IsActive = true,
                            IsArchived = false,
                            Name = "SuperAdmin",
                            UpdatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260)
                        });
                });

            modelBuilder.Entity("DM.DomainModels.RoleAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActionId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleActions");
                });

            modelBuilder.Entity("DM.DomainModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            Email = "POS@gmail.com",
                            IsActive = true,
                            IsArchived = false,
                            Name = "POS",
                            UpdatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            UserType = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("DM.DomainModels.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userRoles");

                    b.HasData(
                        new
                        {
                            Id = "f3df99c7-07fb-4b7f-89e5-89d86b84bd4e",
                            CreatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            CreatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            IsActive = true,
                            IsArchived = false,
                            RoleId = "78f4b56a-3fa3-4067-b641-7adb0a7a2ca7",
                            UpdatedBy = "72990663-2edc-4c10-b331-cd1c65e477e0",
                            UpdatedDate = new DateTime(2024, 10, 29, 7, 47, 20, 293, DateTimeKind.Utc).AddTicks(1260),
                            UserId = "72990663-2edc-4c10-b331-cd1c65e477e0"
                        });
                });

            modelBuilder.Entity("DM.DomainModels.Credential", b =>
                {
                    b.HasOne("DM.DomainModels.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("DM.DomainModels.Credential", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DM.DomainModels.Notification", b =>
                {
                    b.HasOne("DM.DomainModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DM.DomainModels.NotificationSeen", b =>
                {
                    b.HasOne("DM.DomainModels.Notification", "Notification")
                        .WithOne("IsSeen")
                        .HasForeignKey("DM.DomainModels.NotificationSeen", "NotificationId");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("DM.DomainModels.RefreshToken", b =>
                {
                    b.HasOne("DM.DomainModels.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("DM.DomainModels.RefreshToken", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DM.DomainModels.RoleAction", b =>
                {
                    b.HasOne("DM.DomainModels.Actions", "Actions")
                        .WithMany("RoleAction")
                        .HasForeignKey("ActionId");

                    b.HasOne("DM.DomainModels.Role", "Role")
                        .WithMany("RoleAction")
                        .HasForeignKey("RoleId");

                    b.Navigation("Actions");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DM.DomainModels.UserRole", b =>
                {
                    b.HasOne("DM.DomainModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("DM.DomainModels.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DM.DomainModels.Actions", b =>
                {
                    b.Navigation("RoleAction");
                });

            modelBuilder.Entity("DM.DomainModels.Notification", b =>
                {
                    b.Navigation("IsSeen");
                });

            modelBuilder.Entity("DM.DomainModels.Role", b =>
                {
                    b.Navigation("RoleAction");
                });

            modelBuilder.Entity("DM.DomainModels.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("RefreshToken");

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
